// <auto-generated />
using System;
using JiraIntegrationService.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JiraIntegrationService.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260701173506_RemoveSeedDataUseSqlScript")]
    partial class RemoveSeedDataUseSqlScript
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.IssueFieldMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IssueTypeMappingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JiraAllowedValuesJson")
                        .HasMaxLength(20000)
                        .HasColumnType("TEXT");

                    b.Property<string>("JiraAutoCompleteUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("JiraDefaultValueJson")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("JiraField")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("JiraFieldDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("JiraFieldName")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("JiraSchemaCustom")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("JiraSchemaItems")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("JiraSchemaSystem")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("JiraSchemaType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TransformConfigJson")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueShape")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IssueTypeMappingId");

                    b.HasIndex("ProductId", "IssueTypeMappingId", "TemplateCode", "SourcePath")
                        .IsUnique();

                    b.ToTable("IssueFieldMappings", (string)null);
                });

            modelBuilder.Entity("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.IssueFieldMappingTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IssueTypeMappingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TemplateCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IssueTypeMappingId");

                    b.HasIndex("ProductId", "IssueTypeMappingId", "TemplateCode")
                        .IsUnique();

                    b.ToTable("IssueFieldMappingTemplates", (string)null);
                });

            modelBuilder.Entity("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.IssueTypeMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IssueTypeCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("JiraIssueTypeId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("JiraIssueTypeName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "IssueTypeCode")
                        .IsUnique();

                    b.ToTable("IssueTypeMappings");
                });

            modelBuilder.Entity("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.JiraCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordOrToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "IsActive");

                    b.ToTable("JiraCredentials");
                });

            modelBuilder.Entity("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.JiraIssueTypeFieldMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedValuesJson")
                        .HasMaxLength(20000)
                        .HasColumnType("TEXT");

                    b.Property<string>("AutoCompleteUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultValueJson")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasDefaultValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IssueTypeMappingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationsJson")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecommendedValueShape")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecommendedValueType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Required")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SchemaCustom")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SchemaCustomId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SchemaItems")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaSystem")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IssueTypeMappingId");

                    b.HasIndex("ProductId", "IssueTypeMappingId", "FieldId")
                        .IsUnique();

                    b.ToTable("JiraIssueTypeFieldMetadata", (string)null);
                });

            modelBuilder.Entity("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JiraApiBasePath")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("JiraBaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("JiraProjectKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("JiraVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.StatusMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IssueTypeMappingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JiraStatusName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("JiraTransitionId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("JiraTransitionName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StandardStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IssueTypeMappingId");

                    b.HasIndex("ProductId", "IssueTypeMappingId", "StandardStatus", "JiraStatusName")
                        .IsUnique();

                    b.ToTable("StatusMappings");
                });

            modelBuilder.Entity("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.IssueFieldMapping", b =>
                {
                    b.HasOne("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.IssueTypeMapping", "IssueTypeMapping")
                        .WithMany("IssueFieldMappings")
                        .HasForeignKey("IssueTypeMappingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.Product", "Product")
                        .WithMany("IssueFieldMappings")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IssueTypeMapping");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.IssueFieldMappingTemplate", b =>
                {
                    b.HasOne("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.IssueTypeMapping", "IssueTypeMapping")
                        .WithMany("IssueFieldMappingTemplates")
                        .HasForeignKey("IssueTypeMappingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.Product", "Product")
                        .WithMany("IssueFieldMappingTemplates")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IssueTypeMapping");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.IssueTypeMapping", b =>
                {
                    b.HasOne("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.Product", "Product")
                        .WithMany("IssueTypeMappings")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.JiraCredential", b =>
                {
                    b.HasOne("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.Product", "Product")
                        .WithMany("JiraCredentials")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.JiraIssueTypeFieldMetadata", b =>
                {
                    b.HasOne("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.IssueTypeMapping", "IssueTypeMapping")
                        .WithMany("JiraFieldMetadata")
                        .HasForeignKey("IssueTypeMappingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.Product", "Product")
                        .WithMany("JiraIssueTypeFieldMetadata")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IssueTypeMapping");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.StatusMapping", b =>
                {
                    b.HasOne("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.IssueTypeMapping", "IssueTypeMapping")
                        .WithMany("StatusMappings")
                        .HasForeignKey("IssueTypeMappingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.Product", "Product")
                        .WithMany("StatusMappings")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IssueTypeMapping");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.IssueTypeMapping", b =>
                {
                    b.Navigation("IssueFieldMappingTemplates");

                    b.Navigation("IssueFieldMappings");

                    b.Navigation("JiraFieldMetadata");

                    b.Navigation("StatusMappings");
                });

            modelBuilder.Entity("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.Product", b =>
                {
                    b.Navigation("IssueFieldMappingTemplates");

                    b.Navigation("IssueFieldMappings");

                    b.Navigation("IssueTypeMappings");

                    b.Navigation("JiraCredentials");

                    b.Navigation("JiraIssueTypeFieldMetadata");

                    b.Navigation("StatusMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
