// <auto-generated />
using System;
using JiraIntegrationService.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JiraIntegrationService.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.IssueFieldMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IssueTypeMappingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JiraField")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("TransformConfigJson")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueShape")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IssueTypeMappingId");

                    b.HasIndex("ProductId", "IssueTypeMappingId", "SourcePath")
                        .IsUnique();

                    b.ToTable("IssueFieldMappings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsRequired = true,
                            IssueTypeMappingId = 1,
                            JiraField = "summary",
                            ProductId = 1,
                            SortOrder = 10,
                            SourcePath = "data.summary",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueShape = "raw",
                            ValueType = "string"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsRequired = false,
                            IssueTypeMappingId = 1,
                            JiraField = "description",
                            ProductId = 1,
                            SortOrder = 20,
                            SourcePath = "data.description",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueShape = "raw",
                            ValueType = "string"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsRequired = false,
                            IssueTypeMappingId = 1,
                            JiraField = "priority",
                            ProductId = 1,
                            SortOrder = 30,
                            SourcePath = "data.priority",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueShape = "name",
                            ValueType = "string"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsRequired = false,
                            IssueTypeMappingId = 1,
                            JiraField = "customfield_10010",
                            ProductId = 1,
                            SortOrder = 40,
                            SourcePath = "data.customer.code",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueShape = "raw",
                            ValueType = "string"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsRequired = false,
                            IssueTypeMappingId = 1,
                            JiraField = "customfield_10011",
                            ProductId = 1,
                            SortOrder = 50,
                            SourcePath = "data.ticket.url",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueShape = "raw",
                            ValueType = "string"
                        });
                });

            modelBuilder.Entity("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.IssueTypeMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IssueTypeCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("JiraIssueTypeId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("JiraIssueTypeName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "IssueTypeCode")
                        .IsUnique();

                    b.ToTable("IssueTypeMappings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IssueTypeCode = "BUG",
                            JiraIssueTypeName = "Bug",
                            ProductId = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IssueTypeCode = "TASK",
                            JiraIssueTypeName = "Task",
                            ProductId = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.JiraCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordOrToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "IsActive");

                    b.ToTable("JiraCredentials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthType = "Basic",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PasswordOrToken = "change-me",
                            ProductId = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "jira-crm-user"
                        });
                });

            modelBuilder.Entity("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JiraApiBasePath")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("JiraBaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("JiraProjectKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("JiraVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CRM",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            JiraApiBasePath = "/rest/api/2",
                            JiraBaseUrl = "https://jira.example.com",
                            JiraProjectKey = "CRM",
                            JiraVersion = "ServerV2",
                            Name = "CRM",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.StatusMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IssueTypeMappingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JiraStatusName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("JiraTransitionId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("JiraTransitionName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StandardStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IssueTypeMappingId");

                    b.HasIndex("ProductId", "IssueTypeMappingId", "StandardStatus", "JiraStatusName")
                        .IsUnique();

                    b.ToTable("StatusMappings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            IssueTypeMappingId = 1,
                            JiraStatusName = "To Do",
                            ProductId = 1,
                            StandardStatus = "OPEN"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            IssueTypeMappingId = 1,
                            JiraStatusName = "In Progress",
                            JiraTransitionId = "31",
                            JiraTransitionName = "Start Progress",
                            ProductId = 1,
                            StandardStatus = "IN_PROGRESS"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            IssueTypeMappingId = 1,
                            JiraStatusName = "Waiting",
                            JiraTransitionId = "41",
                            JiraTransitionName = "Waiting",
                            ProductId = 1,
                            StandardStatus = "WAITING"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            IssueTypeMappingId = 1,
                            JiraStatusName = "Done",
                            JiraTransitionId = "51",
                            JiraTransitionName = "Done",
                            ProductId = 1,
                            StandardStatus = "DONE"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            IssueTypeMappingId = 1,
                            JiraStatusName = "Cancelled",
                            JiraTransitionId = "61",
                            JiraTransitionName = "Cancel",
                            ProductId = 1,
                            StandardStatus = "CANCELLED"
                        });
                });

            modelBuilder.Entity("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.IssueFieldMapping", b =>
                {
                    b.HasOne("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.IssueTypeMapping", "IssueTypeMapping")
                        .WithMany("IssueFieldMappings")
                        .HasForeignKey("IssueTypeMappingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.Product", "Product")
                        .WithMany("IssueFieldMappings")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IssueTypeMapping");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.IssueTypeMapping", b =>
                {
                    b.HasOne("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.Product", "Product")
                        .WithMany("IssueTypeMappings")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.JiraCredential", b =>
                {
                    b.HasOne("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.Product", "Product")
                        .WithMany("JiraCredentials")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.StatusMapping", b =>
                {
                    b.HasOne("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.IssueTypeMapping", "IssueTypeMapping")
                        .WithMany("StatusMappings")
                        .HasForeignKey("IssueTypeMappingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.Product", "Product")
                        .WithMany("StatusMappings")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IssueTypeMapping");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.IssueTypeMapping", b =>
                {
                    b.Navigation("IssueFieldMappings");

                    b.Navigation("StatusMappings");
                });

            modelBuilder.Entity("JiraIntegrationService.Api.Infrastructure.Persistence.Entities.Product", b =>
                {
                    b.Navigation("IssueFieldMappings");

                    b.Navigation("IssueTypeMappings");

                    b.Navigation("JiraCredentials");

                    b.Navigation("StatusMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
